# Generated by Django 4.2 on 2023-12-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_currency", models.CharField(max_length=3)),
                ("target_currency", models.CharField(max_length=3)),
                ("exchange_rate", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
